# Generated by Django 4.0.5 on 2022-08-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_perex',
            new_name='perex',
        ),
    ]
